version: "3.8"

name: processed-etl

volumes:
  processed:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - processed:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        echo "Installing required tools..."
        apt-get update && apt-get install -y unzip
        pip install gdown

        echo "Resetting /data directory..."
        rm -rf /data/*
        cd /data

        echo "Downloading dataset zip from Google Drive..."
        gdown --id 1BuKyDvKM-UB8yP_xQHVh2T8TjpWY2c2L -O processed_images.zip

        echo "Unzipping dataset..."
        unzip -q processed_images.zip
        rm -f processed_images.zip

        echo "Listing contents of /data after extract stage:"
        ls -l /data

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - processed:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ -z "$RCLONE_CONTAINER" ]; then
          echo "ERROR: RCLONE_CONTAINER is not set"
          exit 1
        fi

        echo "Cleaning up existing contents of container..."
        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true

        echo "Uploading processed data to chi_tacc:$RCLONE_CONTAINER..."
        rclone copy /data chi_tacc:$RCLONE_CONTAINER \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list \
          --retries=10 \
          --low-level-retries=15 \
          --retry-sleep=20s \
          --max-retry-sleep=2m

        echo "Listing directories in container after load stage:"
        rclone lsd chi_tacc:$RCLONE_CONTAINER
